[package]
name = "untitled2"
version = "0.1.0"
authors = ["Alexey <alexey.nebolsin.jr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "*"
regex = "*"
